name: Deploy Frontend on PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ongi-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ongi-frontend:latest

      - name: SSH into GCP and Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST_PROD }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_KEY_PROD }}
          script: |
            set -e
            cd /opt/app/ongi
            docker-compose down
            docker-compose pull
            docker-compose up -d

      - name: Notify Discord on Success
        if: success()
        run: |
          echo '{
            "content": "**✅ PROD 프론트엔드 배포 완료!** 🎉",
            "embeds": [
              {
                "title": "'"${{ github.event.pull_request.title }}"'",
                "url": "'"${{ github.event.pull_request.html_url }}"'",
                "fields": [
                  { "name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true },
                  { "name": "Author", "value": "'"${{ github.actor }}"'", "inline": true }
                ],
                "color": 3066993
              }
            ]
          }' | curl -H "Content-Type: application/json" -X POST -d @- ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          echo '{
            "content": "**❌ PROD 프론트엔드 배포 실패!** 🧨",
            "embeds": [
              {
                "title": "'"${{ github.event.pull_request.title }}"'",
                "url": "'"${{ github.event.pull_request.html_url }}"'",
                "fields": [
                  { "name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true },
                  { "name": "Author", "value": "'"${{ github.actor }}"'", "inline": true }
                ],
                "color": 15158332
              }
            ]
          }' | curl -H "Content-Type: application/json" -X POST -d @- ${{ secrets.DISCORD_WEBHOOK_URL }}
